### ISSUE TITLE
Compared to now -E

### ISSUE THREAD

**Issue by millette** [sergiodxa/now-env#2]
```now -E``` will read your .env file (by default, you can specify another name otherwise).

Trying to figure what else your module provides, compared to the ```now``` cli.

**Comment by sergiodxa** [comment]
This module read your env variables from `now.json`, that's the difference, I prefer to use that file instead of a .env file, this also use the secret syntax of Now (`@key-name`) and allow you to set them in another file.

**Comment by millette** [comment]
Great, thanks for the explanation.

Do you know if now.json is uploaded to now and shared over ```/_src```? If so, might be a good idea to add a note to the readme to keep secret env vars secret.

With an .env file, it's usually specified in .gitignore so it won't be uploaded or shared.

**Comment by sergiodxa** [comment]
Yes, `now.json` is uploaded to Now and it appears on `/_src`.

The `now-secrets.json` I introduced here it's not part of Now and should be added to `.gitignore`, the idea is that your `now.json` used for production is the same as development, you just need to provide your own secrets because you don't have access to the Now secrets.
